/*globals define, _*/
/**
 * Generated by DecoratorGenerator
 */

define([
    'js/Decorators/DecoratorBase',
    './DiagramDesigner/TestDecorator.DiagramDesignerWidget',
    './PartBrowser/TestDecorator.PartBrowserWidget'
], function (DecoratorBase, TestDecoratorDiagramDesignerWidget, TestDecoratorPartBrowserWidget) {

    'use strict';

    var DECORATOR_ID = 'TestDecorator';

    function TestDecorator(params) {
        var opts = _.extend({loggerName: this.DECORATORID}, params);

        DecoratorBase.apply(this, [opts]);

        this.logger.debug('TestDecorator ctor');
    }

    _.extend(TestDecorator.prototype, DecoratorBase.prototype);
    TestDecorator.prototype.DECORATORID = DECORATOR_ID;

    /*********************** OVERRIDE DecoratorBase MEMBERS **************************/

    TestDecorator.prototype.initializeSupportedWidgetMap = function () {
        this.supportedWidgetMap = {
            DiagramDesigner: TestDecoratorDiagramDesignerWidget,
            PartBrowser: TestDecoratorPartBrowserWidget
        };
    };

    return TestDecorator;
});
