/*globals define, _*/
/**
 * Generated by DecoratorGenerator
 */

define([
    'js/Decorators/DecoratorBase',
    './DiagramDesigner/MyNewDecorator.DiagramDesignerWidget',
    './PartBrowser/MyNewDecorator.PartBrowserWidget'
], function (DecoratorBase, MyNewDecoratorDiagramDesignerWidget, MyNewDecoratorPartBrowserWidget) {

    'use strict';

    var DECORATOR_ID = 'MyNewDecorator';

    function MyNewDecorator(params) {
        var opts = _.extend({loggerName: this.DECORATORID}, params);

        DecoratorBase.apply(this, [opts]);

        this.logger.debug('MyNewDecorator ctor');
    }

    _.extend(MyNewDecorator.prototype, DecoratorBase.prototype);
    MyNewDecorator.prototype.DECORATORID = DECORATOR_ID;

    /*********************** OVERRIDE DecoratorBase MEMBERS **************************/

    MyNewDecorator.prototype.initializeSupportedWidgetMap = function () {
        this.supportedWidgetMap = {
            DiagramDesigner: MyNewDecoratorDiagramDesignerWidget,
            PartBrowser: MyNewDecoratorPartBrowserWidget
        };
    };

    return MyNewDecorator;
});
